### ISSUE TITLE
role-postgres seems to need python pip/pip2 -- but only have pip3 after role-python_pip

### ISSUE THREAD

**Issue by BlakeGFitch** [robertdebock/ansible-role-postgres#1]
I am using several of your ansible role repositories. I am getting an error from the postgres role. "Unable to find any of pip2, pip to use.  pip needs to be installed." If I log into the target node, I see that pip/pip2 are not installed but pip3 is. Your role to install python_pip has been run. 

Does postgres need something more than the python_pip role installs?

Thanks for your consideration of this! Your roles look really great.

** OUTPUT **
```
2020-03-09 12:33:22,027 p=28471 u=bfitch n=ansible | <mrdata> ESTABLISH SSH CONNECTION FOR USER: mradmin
2020-03-09 12:33:22,028 p=28471 u=bfitch n=ansible | <mrdata> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="mradmin"' -o ConnectTimeout=10 -o ControlPath=/kyb/agpd/bfitch/.ansible/cp/4778be6951 mrdata '/bin/sh -c '"'"'rm -f -r /home/mradmin/.ansible/tmp/ansible-tmp-1583753601.65-258320175187018/ > /dev/null 2>&1 && sleep 0'"'"''
2020-03-09 12:33:22,050 p=28471 u=bfitch n=ansible | <mrdata> (0, '', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /kyb/agpd/bfitch/.ssh/config\r\ndebug1: /kyb/agpd/bfitch/.ssh/config line 2: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 27439\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
2020-03-09 12:33:22,057 p=25358 u=bfitch n=ansible | fatal: [mrdata]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "psycopg2-binary"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    }
}

MSG:

Unable to find any of pip2, pip to use.  pip needs to be installed.

2020-03-09 12:33:22,059 p=25358 u=bfitch n=ansible | PLAY RECAP ****************************************************************************************************************************************************
2020-03-09 12:33:22,060 p=25358 u=bfitch n=ansible | mrdata                     : ok=126  changed=0    unreachable=0    failed=1    skipped=110  rescued=0    ignored=0
```
The playbook is:
```
(ansible) bfitch@oak:~/install-mrdata-server$ cat mrdata.playbook.yml 
---
- hosts: servers
  vars: 
     java_version: 8
     tomcat_version: 7
     postgres_databases:
       - name: test_db
     postgres_users:
       - name: test_user_with_pass
         password: "MyCoMpLeXpAsSwOrD"
       - name: test_user_with_db
         password: "MyCoMpLeXpAsSwOrD"
         db: test_db

  roles:
     - ansible-hardening
     - robertdebock.bootstrap
     - robertdebock.update
     - robertdebock.common
     - robertdebock.fail2ban
     - robertdebock.firewall
     - robertdebock.python_pip
     - robertdebock.java
     - robertdebock.tomcat
     - robertdebock.postgres
     - robertdebock.docker
     - ansible-role-xnat
```

**Expected behavior**
Postgres install to complete

**Environment**
- Control node OS: Ubuntu 18.04
- Control node Ansible version: ansible 2.10.0.dev0
- Managed node OS: Ubuntu 16.04 server

**Comment by BlakeGFitch** [comment]
The following modification causes the playbook to run through, including finding pip. But it's probably not the right way to do it. (Added - python-pip - python-setuptools to Debian: stanza.)

```
(ansible) bfitch@oak:~/install-mrdata-server$ cat ~/.ansible/roles/robertdebock.python_pip/vars/main.yml 
---
# vars file for python_pip
_python_pip_packages:
  Alpine:
    - py-pip
    - py-setuptools
    - python2-dev
  Debian:
    - python-pip
    - python-setuptools
    - python3-pip
    - python3-setuptools
  RedHat-7:
    - python2-pip
    - python-setuptools
  RedHat:
    - python3-pip
    - python3-setuptools
  Suse:
    - python-pip
    - python-setuptools

python_pip_packages: "{{ _python_pip_packages[ansible_os_family ~ '-' ~ ansible_distribution_major_version] | default(_python_pip_packages[ansible_os_family] | default(_python_pip_packages['default'])) }}"
```
