### ISSUE TITLE
Undocumented variables

### ISSUE THREAD

**Issue by bbaassssiiee** [robertdebock/ansible-role-postgres#2]
Please document with an example in `README.md` how to use these vars:

```yaml
- postgres_databases:
     - name: 
       encoding: 
       conn_limit: 
       owner: 
       trust_input: 
       state: 
- postgres_users:
     - name: 
       db: 
       password: 
       expires: 
```
